// Generated by tools/gen_catalog.py — do not edit by hand.
// Sources: supabase/migrations/0002_generic_metrics.sql, tools/metric_names_de.py
//
// Every HealthKit type the system knows about (191 of them). Types resolve
// from their raw identifier at runtime rather than from compile-time enum cases,
// so a type that a given iOS version does not have simply resolves to nil and
// drops out of the picker instead of breaking the build.

import Foundation
import HealthKit

enum MetricKind: String, Sendable { case quantity, category, workout }
enum MetricAggregation: String, Sendable { case sum, avg, latest, duration, count, max }
enum MetricSensitivity: String, Sendable { case standard, sensitive }

enum MetricCategory: String, Sendable, CaseIterable, Identifiable {
    case activity
    case body
    case fitness
    case hearing
    case heart
    case lab
    case mindfulness
    case mobility
    case nutrition
    case other
    case reproductive
    case respiratory
    case sleep
    case symptoms
    case vitals

    var id: String { rawValue }

    var symbol: String {
        switch self {
        case .activity: "figure.walk"
        case .body: "figure.stand"
        case .fitness: "figure.run"
        case .hearing: "ear"
        case .heart: "heart.fill"
        case .lab: "testtube.2"
        case .mindfulness: "brain.head.profile"
        case .mobility: "figure.walk.motion"
        case .nutrition: "fork.knife"
        case .other: "square.grid.2x2"
        case .reproductive: "figure.dress.line.vertical.figure"
        case .respiratory: "lungs.fill"
        case .sleep: "bed.double.fill"
        case .symptoms: "stethoscope"
        case .vitals: "waveform.path.ecg"
        }
    }

    /// English source string; the String Catalog supplies the German.
    private var sourceTitle: String {
        switch self {
        case .activity: "Activity"
        case .body: "Body Measurements"
        case .fitness: "Fitness"
        case .hearing: "Hearing"
        case .heart: "Heart"
        case .lab: "Lab Results"
        case .mindfulness: "Mindfulness"
        case .mobility: "Mobility"
        case .nutrition: "Nutrition"
        case .other: "Other"
        case .reproductive: "Reproductive Health"
        case .respiratory: "Respiratory"
        case .sleep: "Sleep"
        case .symptoms: "Symptoms"
        case .vitals: "Vitals"
        }
    }

    var title: String { String(localized: .init(sourceTitle)) }
}

struct MetricDescriptor: Sendable, Hashable, Identifiable {
    let key: String
    let hkIdentifier: String
    let kind: MetricKind
    let name: String
    let category: MetricCategory
    let unit: String?
    let aggregation: MetricAggregation
    let sensitivity: MetricSensitivity

    var id: String { key }

    /// Looked up at runtime because `name` is data, not a literal.
    var localizedName: String { String(localized: .init(name)) }

    /// The HealthKit type to request, or nil when this OS has no such type.
    var objectType: HKObjectType? {
        switch kind {
        case .quantity:
            HKObjectType.quantityType(forIdentifier: .init(rawValue: hkIdentifier))
        case .category:
            HKObjectType.categoryType(forIdentifier: .init(rawValue: hkIdentifier))
        case .workout:
            HKObjectType.workoutType()
        }
    }
}

enum MetricCatalog {
    static let all: [MetricDescriptor] = [
        .init(key: "body_mass_index", hkIdentifier: "HKQuantityTypeIdentifierBodyMassIndex", kind: .quantity, name: "Body Mass Index", category: .body, unit: "count", aggregation: .avg, sensitivity: .standard),
        .init(key: "body_fat_percentage", hkIdentifier: "HKQuantityTypeIdentifierBodyFatPercentage", kind: .quantity, name: "Body Fat Percentage", category: .body, unit: "%", aggregation: .avg, sensitivity: .standard),
        .init(key: "height", hkIdentifier: "HKQuantityTypeIdentifierHeight", kind: .quantity, name: "Height", category: .body, unit: "m", aggregation: .latest, sensitivity: .standard),
        .init(key: "body_mass", hkIdentifier: "HKQuantityTypeIdentifierBodyMass", kind: .quantity, name: "Body Mass", category: .body, unit: "kg", aggregation: .avg, sensitivity: .standard),
        .init(key: "lean_body_mass", hkIdentifier: "HKQuantityTypeIdentifierLeanBodyMass", kind: .quantity, name: "Lean Body Mass", category: .body, unit: "kg", aggregation: .avg, sensitivity: .standard),
        .init(key: "heart_rate", hkIdentifier: "HKQuantityTypeIdentifierHeartRate", kind: .quantity, name: "Heart Rate", category: .heart, unit: "count/min", aggregation: .avg, sensitivity: .standard),
        .init(key: "step_count", hkIdentifier: "HKQuantityTypeIdentifierStepCount", kind: .quantity, name: "Steps", category: .activity, unit: "count", aggregation: .sum, sensitivity: .standard),
        .init(key: "distance_walking_running", hkIdentifier: "HKQuantityTypeIdentifierDistanceWalkingRunning", kind: .quantity, name: "Walking + Running Distance", category: .activity, unit: "m", aggregation: .sum, sensitivity: .standard),
        .init(key: "distance_cycling", hkIdentifier: "HKQuantityTypeIdentifierDistanceCycling", kind: .quantity, name: "Cycling Distance", category: .activity, unit: "m", aggregation: .sum, sensitivity: .standard),
        .init(key: "basal_energy_burned", hkIdentifier: "HKQuantityTypeIdentifierBasalEnergyBurned", kind: .quantity, name: "Resting Energy", category: .activity, unit: "kcal", aggregation: .sum, sensitivity: .standard),
        .init(key: "active_energy_burned", hkIdentifier: "HKQuantityTypeIdentifierActiveEnergyBurned", kind: .quantity, name: "Active Energy", category: .activity, unit: "kcal", aggregation: .sum, sensitivity: .standard),
        .init(key: "flights_climbed", hkIdentifier: "HKQuantityTypeIdentifierFlightsClimbed", kind: .quantity, name: "Flights Climbed", category: .activity, unit: "count", aggregation: .sum, sensitivity: .standard),
        .init(key: "nike_fuel", hkIdentifier: "HKQuantityTypeIdentifierNikeFuel", kind: .quantity, name: "NikeFuel", category: .activity, unit: "count", aggregation: .sum, sensitivity: .standard),
        .init(key: "oxygen_saturation", hkIdentifier: "HKQuantityTypeIdentifierOxygenSaturation", kind: .quantity, name: "Blood Oxygen", category: .vitals, unit: "%", aggregation: .avg, sensitivity: .standard),
        .init(key: "blood_glucose", hkIdentifier: "HKQuantityTypeIdentifierBloodGlucose", kind: .quantity, name: "Blood Glucose", category: .lab, unit: "mg/dL", aggregation: .avg, sensitivity: .sensitive),
        .init(key: "blood_pressure_systolic", hkIdentifier: "HKQuantityTypeIdentifierBloodPressureSystolic", kind: .quantity, name: "Blood Pressure (Systolic)", category: .vitals, unit: "mmHg", aggregation: .avg, sensitivity: .standard),
        .init(key: "blood_pressure_diastolic", hkIdentifier: "HKQuantityTypeIdentifierBloodPressureDiastolic", kind: .quantity, name: "Blood Pressure (Diastolic)", category: .vitals, unit: "mmHg", aggregation: .avg, sensitivity: .standard),
        .init(key: "blood_alcohol_content", hkIdentifier: "HKQuantityTypeIdentifierBloodAlcoholContent", kind: .quantity, name: "Blood Alcohol Content", category: .lab, unit: "%", aggregation: .avg, sensitivity: .sensitive),
        .init(key: "peripheral_perfusion_index", hkIdentifier: "HKQuantityTypeIdentifierPeripheralPerfusionIndex", kind: .quantity, name: "Peripheral Perfusion Index", category: .vitals, unit: "%", aggregation: .avg, sensitivity: .standard),
        .init(key: "forced_vital_capacity", hkIdentifier: "HKQuantityTypeIdentifierForcedVitalCapacity", kind: .quantity, name: "Forced Vital Capacity", category: .respiratory, unit: "L", aggregation: .avg, sensitivity: .standard),
        .init(key: "forced_expiratory_volume1", hkIdentifier: "HKQuantityTypeIdentifierForcedExpiratoryVolume1", kind: .quantity, name: "Forced Expiratory Volume (1s)", category: .respiratory, unit: "L", aggregation: .avg, sensitivity: .standard),
        .init(key: "peak_expiratory_flow_rate", hkIdentifier: "HKQuantityTypeIdentifierPeakExpiratoryFlowRate", kind: .quantity, name: "Peak Expiratory Flow Rate", category: .respiratory, unit: "L/min", aggregation: .avg, sensitivity: .standard),
        .init(key: "number_of_times_fallen", hkIdentifier: "HKQuantityTypeIdentifierNumberOfTimesFallen", kind: .quantity, name: "Number of Times Fallen", category: .mobility, unit: "count", aggregation: .sum, sensitivity: .standard),
        .init(key: "inhaler_usage", hkIdentifier: "HKQuantityTypeIdentifierInhalerUsage", kind: .quantity, name: "Inhaler Usage", category: .respiratory, unit: "count", aggregation: .sum, sensitivity: .sensitive),
        .init(key: "respiratory_rate", hkIdentifier: "HKQuantityTypeIdentifierRespiratoryRate", kind: .quantity, name: "Respiratory Rate", category: .respiratory, unit: "count/min", aggregation: .avg, sensitivity: .standard),
        .init(key: "body_temperature", hkIdentifier: "HKQuantityTypeIdentifierBodyTemperature", kind: .quantity, name: "Body Temperature", category: .vitals, unit: "degC", aggregation: .avg, sensitivity: .standard),
        .init(key: "dietary_fat_total", hkIdentifier: "HKQuantityTypeIdentifierDietaryFatTotal", kind: .quantity, name: "Total Fat", category: .nutrition, unit: "g", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_fat_polyunsaturated", hkIdentifier: "HKQuantityTypeIdentifierDietaryFatPolyunsaturated", kind: .quantity, name: "Polyunsaturated Fat", category: .nutrition, unit: "g", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_fat_monounsaturated", hkIdentifier: "HKQuantityTypeIdentifierDietaryFatMonounsaturated", kind: .quantity, name: "Monounsaturated Fat", category: .nutrition, unit: "g", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_fat_saturated", hkIdentifier: "HKQuantityTypeIdentifierDietaryFatSaturated", kind: .quantity, name: "Saturated Fat", category: .nutrition, unit: "g", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_cholesterol", hkIdentifier: "HKQuantityTypeIdentifierDietaryCholesterol", kind: .quantity, name: "Cholesterol", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_sodium", hkIdentifier: "HKQuantityTypeIdentifierDietarySodium", kind: .quantity, name: "Sodium", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_carbohydrates", hkIdentifier: "HKQuantityTypeIdentifierDietaryCarbohydrates", kind: .quantity, name: "Carbohydrates", category: .nutrition, unit: "g", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_fiber", hkIdentifier: "HKQuantityTypeIdentifierDietaryFiber", kind: .quantity, name: "Fiber", category: .nutrition, unit: "g", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_sugar", hkIdentifier: "HKQuantityTypeIdentifierDietarySugar", kind: .quantity, name: "Sugar", category: .nutrition, unit: "g", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_energy_consumed", hkIdentifier: "HKQuantityTypeIdentifierDietaryEnergyConsumed", kind: .quantity, name: "Dietary Energy", category: .nutrition, unit: "kcal", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_protein", hkIdentifier: "HKQuantityTypeIdentifierDietaryProtein", kind: .quantity, name: "Protein", category: .nutrition, unit: "g", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_vitamin_a", hkIdentifier: "HKQuantityTypeIdentifierDietaryVitaminA", kind: .quantity, name: "Vitamin A", category: .nutrition, unit: "mcg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_vitamin_b6", hkIdentifier: "HKQuantityTypeIdentifierDietaryVitaminB6", kind: .quantity, name: "Vitamin B6", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_vitamin_b12", hkIdentifier: "HKQuantityTypeIdentifierDietaryVitaminB12", kind: .quantity, name: "Vitamin B12", category: .nutrition, unit: "mcg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_vitamin_c", hkIdentifier: "HKQuantityTypeIdentifierDietaryVitaminC", kind: .quantity, name: "Vitamin C", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_vitamin_d", hkIdentifier: "HKQuantityTypeIdentifierDietaryVitaminD", kind: .quantity, name: "Vitamin D", category: .nutrition, unit: "mcg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_vitamin_e", hkIdentifier: "HKQuantityTypeIdentifierDietaryVitaminE", kind: .quantity, name: "Vitamin E", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_vitamin_k", hkIdentifier: "HKQuantityTypeIdentifierDietaryVitaminK", kind: .quantity, name: "Vitamin K", category: .nutrition, unit: "mcg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_calcium", hkIdentifier: "HKQuantityTypeIdentifierDietaryCalcium", kind: .quantity, name: "Calcium", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_iron", hkIdentifier: "HKQuantityTypeIdentifierDietaryIron", kind: .quantity, name: "Iron", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_thiamin", hkIdentifier: "HKQuantityTypeIdentifierDietaryThiamin", kind: .quantity, name: "Thiamin", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_riboflavin", hkIdentifier: "HKQuantityTypeIdentifierDietaryRiboflavin", kind: .quantity, name: "Riboflavin", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_niacin", hkIdentifier: "HKQuantityTypeIdentifierDietaryNiacin", kind: .quantity, name: "Niacin", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_folate", hkIdentifier: "HKQuantityTypeIdentifierDietaryFolate", kind: .quantity, name: "Folate", category: .nutrition, unit: "mcg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_biotin", hkIdentifier: "HKQuantityTypeIdentifierDietaryBiotin", kind: .quantity, name: "Biotin", category: .nutrition, unit: "mcg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_pantothenic_acid", hkIdentifier: "HKQuantityTypeIdentifierDietaryPantothenicAcid", kind: .quantity, name: "Pantothenic Acid", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_phosphorus", hkIdentifier: "HKQuantityTypeIdentifierDietaryPhosphorus", kind: .quantity, name: "Phosphorus", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_iodine", hkIdentifier: "HKQuantityTypeIdentifierDietaryIodine", kind: .quantity, name: "Iodine", category: .nutrition, unit: "mcg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_magnesium", hkIdentifier: "HKQuantityTypeIdentifierDietaryMagnesium", kind: .quantity, name: "Magnesium", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_zinc", hkIdentifier: "HKQuantityTypeIdentifierDietaryZinc", kind: .quantity, name: "Zinc", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_selenium", hkIdentifier: "HKQuantityTypeIdentifierDietarySelenium", kind: .quantity, name: "Selenium", category: .nutrition, unit: "mcg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_copper", hkIdentifier: "HKQuantityTypeIdentifierDietaryCopper", kind: .quantity, name: "Copper", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_manganese", hkIdentifier: "HKQuantityTypeIdentifierDietaryManganese", kind: .quantity, name: "Manganese", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_chromium", hkIdentifier: "HKQuantityTypeIdentifierDietaryChromium", kind: .quantity, name: "Chromium", category: .nutrition, unit: "mcg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_molybdenum", hkIdentifier: "HKQuantityTypeIdentifierDietaryMolybdenum", kind: .quantity, name: "Molybdenum", category: .nutrition, unit: "mcg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_chloride", hkIdentifier: "HKQuantityTypeIdentifierDietaryChloride", kind: .quantity, name: "Chloride", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_potassium", hkIdentifier: "HKQuantityTypeIdentifierDietaryPotassium", kind: .quantity, name: "Potassium", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "dietary_caffeine", hkIdentifier: "HKQuantityTypeIdentifierDietaryCaffeine", kind: .quantity, name: "Caffeine", category: .nutrition, unit: "mg", aggregation: .sum, sensitivity: .standard),
        .init(key: "basal_body_temperature", hkIdentifier: "HKQuantityTypeIdentifierBasalBodyTemperature", kind: .quantity, name: "Basal Body Temperature", category: .reproductive, unit: "degC", aggregation: .avg, sensitivity: .sensitive),
        .init(key: "dietary_water", hkIdentifier: "HKQuantityTypeIdentifierDietaryWater", kind: .quantity, name: "Water", category: .nutrition, unit: "mL", aggregation: .sum, sensitivity: .standard),
        .init(key: "uv_exposure", hkIdentifier: "HKQuantityTypeIdentifierUVExposure", kind: .quantity, name: "UV Index", category: .other, unit: "count", aggregation: .avg, sensitivity: .standard),
        .init(key: "electrodermal_activity", hkIdentifier: "HKQuantityTypeIdentifierElectrodermalActivity", kind: .quantity, name: "Electrodermal Activity", category: .other, unit: "siemens", aggregation: .avg, sensitivity: .standard),
        .init(key: "apple_exercise_time", hkIdentifier: "HKQuantityTypeIdentifierAppleExerciseTime", kind: .quantity, name: "Exercise Minutes", category: .activity, unit: "min", aggregation: .sum, sensitivity: .standard),
        .init(key: "distance_wheelchair", hkIdentifier: "HKQuantityTypeIdentifierDistanceWheelchair", kind: .quantity, name: "Wheelchair Distance", category: .activity, unit: "m", aggregation: .sum, sensitivity: .standard),
        .init(key: "push_count", hkIdentifier: "HKQuantityTypeIdentifierPushCount", kind: .quantity, name: "Pushes", category: .activity, unit: "count", aggregation: .sum, sensitivity: .standard),
        .init(key: "distance_swimming", hkIdentifier: "HKQuantityTypeIdentifierDistanceSwimming", kind: .quantity, name: "Swimming Distance", category: .activity, unit: "m", aggregation: .sum, sensitivity: .standard),
        .init(key: "swimming_stroke_count", hkIdentifier: "HKQuantityTypeIdentifierSwimmingStrokeCount", kind: .quantity, name: "Swimming Strokes", category: .activity, unit: "count", aggregation: .sum, sensitivity: .standard),
        .init(key: "waist_circumference", hkIdentifier: "HKQuantityTypeIdentifierWaistCircumference", kind: .quantity, name: "Waist Circumference", category: .body, unit: "m", aggregation: .avg, sensitivity: .standard),
        .init(key: "vo2_max", hkIdentifier: "HKQuantityTypeIdentifierVO2Max", kind: .quantity, name: "VO2 Max", category: .fitness, unit: "mL/kg*min", aggregation: .avg, sensitivity: .standard),
        .init(key: "distance_downhill_snow_sports", hkIdentifier: "HKQuantityTypeIdentifierDistanceDownhillSnowSports", kind: .quantity, name: "Downhill Snow Sports Distance", category: .activity, unit: "m", aggregation: .sum, sensitivity: .standard),
        .init(key: "insulin_delivery", hkIdentifier: "HKQuantityTypeIdentifierInsulinDelivery", kind: .quantity, name: "Insulin Delivery", category: .lab, unit: "IU", aggregation: .sum, sensitivity: .sensitive),
        .init(key: "resting_heart_rate", hkIdentifier: "HKQuantityTypeIdentifierRestingHeartRate", kind: .quantity, name: "Resting Heart Rate", category: .heart, unit: "count/min", aggregation: .avg, sensitivity: .standard),
        .init(key: "walking_heart_rate_average", hkIdentifier: "HKQuantityTypeIdentifierWalkingHeartRateAverage", kind: .quantity, name: "Walking Heart Rate Average", category: .heart, unit: "count/min", aggregation: .avg, sensitivity: .standard),
        .init(key: "heart_rate_variability_sdnn", hkIdentifier: "HKQuantityTypeIdentifierHeartRateVariabilitySDNN", kind: .quantity, name: "Heart Rate Variability (SDNN)", category: .heart, unit: "ms", aggregation: .avg, sensitivity: .standard),
        .init(key: "apple_stand_time", hkIdentifier: "HKQuantityTypeIdentifierAppleStandTime", kind: .quantity, name: "Stand Minutes", category: .activity, unit: "min", aggregation: .sum, sensitivity: .standard),
        .init(key: "environmental_audio_exposure", hkIdentifier: "HKQuantityTypeIdentifierEnvironmentalAudioExposure", kind: .quantity, name: "Environmental Sound Levels", category: .hearing, unit: "dBASPL", aggregation: .avg, sensitivity: .standard),
        .init(key: "headphone_audio_exposure", hkIdentifier: "HKQuantityTypeIdentifierHeadphoneAudioExposure", kind: .quantity, name: "Headphone Audio Levels", category: .hearing, unit: "dBASPL", aggregation: .avg, sensitivity: .standard),
        .init(key: "six_minute_walk_test_distance", hkIdentifier: "HKQuantityTypeIdentifierSixMinuteWalkTestDistance", kind: .quantity, name: "Six-Minute Walk Distance", category: .mobility, unit: "m", aggregation: .avg, sensitivity: .standard),
        .init(key: "stair_ascent_speed", hkIdentifier: "HKQuantityTypeIdentifierStairAscentSpeed", kind: .quantity, name: "Stair Ascent Speed", category: .mobility, unit: "m/s", aggregation: .avg, sensitivity: .standard),
        .init(key: "stair_descent_speed", hkIdentifier: "HKQuantityTypeIdentifierStairDescentSpeed", kind: .quantity, name: "Stair Descent Speed", category: .mobility, unit: "m/s", aggregation: .avg, sensitivity: .standard),
        .init(key: "walking_asymmetry_percentage", hkIdentifier: "HKQuantityTypeIdentifierWalkingAsymmetryPercentage", kind: .quantity, name: "Walking Asymmetry", category: .mobility, unit: "%", aggregation: .avg, sensitivity: .standard),
        .init(key: "walking_double_support_percentage", hkIdentifier: "HKQuantityTypeIdentifierWalkingDoubleSupportPercentage", kind: .quantity, name: "Double Support Time", category: .mobility, unit: "%", aggregation: .avg, sensitivity: .standard),
        .init(key: "walking_speed", hkIdentifier: "HKQuantityTypeIdentifierWalkingSpeed", kind: .quantity, name: "Walking Speed", category: .mobility, unit: "m/s", aggregation: .avg, sensitivity: .standard),
        .init(key: "walking_step_length", hkIdentifier: "HKQuantityTypeIdentifierWalkingStepLength", kind: .quantity, name: "Walking Step Length", category: .mobility, unit: "m", aggregation: .avg, sensitivity: .standard),
        .init(key: "apple_move_time", hkIdentifier: "HKQuantityTypeIdentifierAppleMoveTime", kind: .quantity, name: "Move Minutes", category: .activity, unit: "min", aggregation: .sum, sensitivity: .standard),
        .init(key: "apple_walking_steadiness", hkIdentifier: "HKQuantityTypeIdentifierAppleWalkingSteadiness", kind: .quantity, name: "Walking Steadiness", category: .mobility, unit: "%", aggregation: .avg, sensitivity: .standard),
        .init(key: "number_of_alcoholic_beverages", hkIdentifier: "HKQuantityTypeIdentifierNumberOfAlcoholicBeverages", kind: .quantity, name: "Alcoholic Beverages", category: .nutrition, unit: "count", aggregation: .sum, sensitivity: .sensitive),
        .init(key: "heart_rate_recovery_one_minute", hkIdentifier: "HKQuantityTypeIdentifierHeartRateRecoveryOneMinute", kind: .quantity, name: "Cardio Recovery", category: .heart, unit: "count/min", aggregation: .avg, sensitivity: .standard),
        .init(key: "running_ground_contact_time", hkIdentifier: "HKQuantityTypeIdentifierRunningGroundContactTime", kind: .quantity, name: "Ground Contact Time", category: .fitness, unit: "ms", aggregation: .avg, sensitivity: .standard),
        .init(key: "running_stride_length", hkIdentifier: "HKQuantityTypeIdentifierRunningStrideLength", kind: .quantity, name: "Running Stride Length", category: .fitness, unit: "m", aggregation: .avg, sensitivity: .standard),
        .init(key: "running_vertical_oscillation", hkIdentifier: "HKQuantityTypeIdentifierRunningVerticalOscillation", kind: .quantity, name: "Vertical Oscillation", category: .fitness, unit: "cm", aggregation: .avg, sensitivity: .standard),
        .init(key: "running_power", hkIdentifier: "HKQuantityTypeIdentifierRunningPower", kind: .quantity, name: "Running Power", category: .fitness, unit: "W", aggregation: .avg, sensitivity: .standard),
        .init(key: "running_speed", hkIdentifier: "HKQuantityTypeIdentifierRunningSpeed", kind: .quantity, name: "Running Speed", category: .fitness, unit: "m/s", aggregation: .avg, sensitivity: .standard),
        .init(key: "atrial_fibrillation_burden", hkIdentifier: "HKQuantityTypeIdentifierAtrialFibrillationBurden", kind: .quantity, name: "AFib History", category: .heart, unit: "%", aggregation: .avg, sensitivity: .sensitive),
        .init(key: "apple_sleeping_wrist_temperature", hkIdentifier: "HKQuantityTypeIdentifierAppleSleepingWristTemperature", kind: .quantity, name: "Wrist Temperature", category: .sleep, unit: "degC", aggregation: .avg, sensitivity: .standard),
        .init(key: "underwater_depth", hkIdentifier: "HKQuantityTypeIdentifierUnderwaterDepth", kind: .quantity, name: "Underwater Depth", category: .fitness, unit: "m", aggregation: .max, sensitivity: .standard),
        .init(key: "water_temperature", hkIdentifier: "HKQuantityTypeIdentifierWaterTemperature", kind: .quantity, name: "Water Temperature", category: .other, unit: "degC", aggregation: .avg, sensitivity: .standard),
        .init(key: "cycling_cadence", hkIdentifier: "HKQuantityTypeIdentifierCyclingCadence", kind: .quantity, name: "Cycling Cadence", category: .fitness, unit: "count/min", aggregation: .avg, sensitivity: .standard),
        .init(key: "cycling_functional_threshold_power", hkIdentifier: "HKQuantityTypeIdentifierCyclingFunctionalThresholdPower", kind: .quantity, name: "Cycling FTP", category: .fitness, unit: "W", aggregation: .avg, sensitivity: .standard),
        .init(key: "cycling_power", hkIdentifier: "HKQuantityTypeIdentifierCyclingPower", kind: .quantity, name: "Cycling Power", category: .fitness, unit: "W", aggregation: .avg, sensitivity: .standard),
        .init(key: "cycling_speed", hkIdentifier: "HKQuantityTypeIdentifierCyclingSpeed", kind: .quantity, name: "Cycling Speed", category: .fitness, unit: "m/s", aggregation: .avg, sensitivity: .standard),
        .init(key: "environmental_sound_reduction", hkIdentifier: "HKQuantityTypeIdentifierEnvironmentalSoundReduction", kind: .quantity, name: "Environmental Sound Reduction", category: .hearing, unit: "dBASPL", aggregation: .avg, sensitivity: .standard),
        .init(key: "physical_effort", hkIdentifier: "HKQuantityTypeIdentifierPhysicalEffort", kind: .quantity, name: "Physical Effort", category: .activity, unit: "kcal/kg*hr", aggregation: .avg, sensitivity: .standard),
        .init(key: "time_in_daylight", hkIdentifier: "HKQuantityTypeIdentifierTimeInDaylight", kind: .quantity, name: "Time in Daylight", category: .activity, unit: "min", aggregation: .sum, sensitivity: .standard),
        .init(key: "workout_effort_score", hkIdentifier: "HKQuantityTypeIdentifierWorkoutEffortScore", kind: .quantity, name: "Workout Effort Score", category: .fitness, unit: "effortScore", aggregation: .avg, sensitivity: .standard),
        .init(key: "cross_country_skiing_speed", hkIdentifier: "HKQuantityTypeIdentifierCrossCountrySkiingSpeed", kind: .quantity, name: "Cross-Country Skiing Speed", category: .fitness, unit: "m/s", aggregation: .avg, sensitivity: .standard),
        .init(key: "distance_cross_country_skiing", hkIdentifier: "HKQuantityTypeIdentifierDistanceCrossCountrySkiing", kind: .quantity, name: "Cross-Country Skiing Distance", category: .activity, unit: "m", aggregation: .sum, sensitivity: .standard),
        .init(key: "distance_paddle_sports", hkIdentifier: "HKQuantityTypeIdentifierDistancePaddleSports", kind: .quantity, name: "Paddle Sports Distance", category: .activity, unit: "m", aggregation: .sum, sensitivity: .standard),
        .init(key: "distance_rowing", hkIdentifier: "HKQuantityTypeIdentifierDistanceRowing", kind: .quantity, name: "Rowing Distance", category: .activity, unit: "m", aggregation: .sum, sensitivity: .standard),
        .init(key: "distance_skating_sports", hkIdentifier: "HKQuantityTypeIdentifierDistanceSkatingSports", kind: .quantity, name: "Skating Sports Distance", category: .activity, unit: "m", aggregation: .sum, sensitivity: .standard),
        .init(key: "estimated_workout_effort_score", hkIdentifier: "HKQuantityTypeIdentifierEstimatedWorkoutEffortScore", kind: .quantity, name: "Estimated Workout Effort", category: .fitness, unit: "effortScore", aggregation: .avg, sensitivity: .standard),
        .init(key: "paddle_sports_speed", hkIdentifier: "HKQuantityTypeIdentifierPaddleSportsSpeed", kind: .quantity, name: "Paddle Sports Speed", category: .fitness, unit: "m/s", aggregation: .avg, sensitivity: .standard),
        .init(key: "rowing_speed", hkIdentifier: "HKQuantityTypeIdentifierRowingSpeed", kind: .quantity, name: "Rowing Speed", category: .fitness, unit: "m/s", aggregation: .avg, sensitivity: .standard),
        .init(key: "apple_sleeping_breathing_disturbances", hkIdentifier: "HKQuantityTypeIdentifierAppleSleepingBreathingDisturbances", kind: .quantity, name: "Breathing Disturbances", category: .sleep, unit: "count", aggregation: .avg, sensitivity: .standard),
        .init(key: "sleep_analysis", hkIdentifier: "HKCategoryTypeIdentifierSleepAnalysis", kind: .category, name: "Sleep Analysis", category: .sleep, unit: "min", aggregation: .duration, sensitivity: .standard),
        .init(key: "apple_stand_hour", hkIdentifier: "HKCategoryTypeIdentifierAppleStandHour", kind: .category, name: "Stand Hours", category: .activity, unit: "count", aggregation: .count, sensitivity: .standard),
        .init(key: "cervical_mucus_quality", hkIdentifier: "HKCategoryTypeIdentifierCervicalMucusQuality", kind: .category, name: "Cervical Mucus Quality", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "ovulation_test_result", hkIdentifier: "HKCategoryTypeIdentifierOvulationTestResult", kind: .category, name: "Ovulation Test Result", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "menstrual_flow", hkIdentifier: "HKCategoryTypeIdentifierMenstrualFlow", kind: .category, name: "Menstrual Flow", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "intermenstrual_bleeding", hkIdentifier: "HKCategoryTypeIdentifierIntermenstrualBleeding", kind: .category, name: "Intermenstrual Bleeding", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "sexual_activity", hkIdentifier: "HKCategoryTypeIdentifierSexualActivity", kind: .category, name: "Sexual Activity", category: .reproductive, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "mindful_session", hkIdentifier: "HKCategoryTypeIdentifierMindfulSession", kind: .category, name: "Mindful Minutes", category: .mindfulness, unit: "min", aggregation: .duration, sensitivity: .standard),
        .init(key: "high_heart_rate_event", hkIdentifier: "HKCategoryTypeIdentifierHighHeartRateEvent", kind: .category, name: "High Heart Rate Events", category: .heart, unit: "count", aggregation: .count, sensitivity: .standard),
        .init(key: "low_heart_rate_event", hkIdentifier: "HKCategoryTypeIdentifierLowHeartRateEvent", kind: .category, name: "Low Heart Rate Events", category: .heart, unit: "count", aggregation: .count, sensitivity: .standard),
        .init(key: "irregular_heart_rhythm_event", hkIdentifier: "HKCategoryTypeIdentifierIrregularHeartRhythmEvent", kind: .category, name: "Irregular Rhythm Events", category: .heart, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "audio_exposure_event", hkIdentifier: "HKCategoryTypeIdentifierAudioExposureEvent", kind: .category, name: "Audio Exposure Events", category: .hearing, unit: "count", aggregation: .count, sensitivity: .standard),
        .init(key: "toothbrushing_event", hkIdentifier: "HKCategoryTypeIdentifierToothbrushingEvent", kind: .category, name: "Toothbrushing", category: .other, unit: "min", aggregation: .duration, sensitivity: .standard),
        .init(key: "abdominal_cramps", hkIdentifier: "HKCategoryTypeIdentifierAbdominalCramps", kind: .category, name: "Abdominal Cramps", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "acne", hkIdentifier: "HKCategoryTypeIdentifierAcne", kind: .category, name: "Acne", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "appetite_changes", hkIdentifier: "HKCategoryTypeIdentifierAppetiteChanges", kind: .category, name: "Appetite Changes", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "generalized_body_ache", hkIdentifier: "HKCategoryTypeIdentifierGeneralizedBodyAche", kind: .category, name: "Body and Muscle Ache", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "bloating", hkIdentifier: "HKCategoryTypeIdentifierBloating", kind: .category, name: "Bloating", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "breast_pain", hkIdentifier: "HKCategoryTypeIdentifierBreastPain", kind: .category, name: "Breast Pain", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "chest_tightness_or_pain", hkIdentifier: "HKCategoryTypeIdentifierChestTightnessOrPain", kind: .category, name: "Chest Tightness or Pain", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "chills", hkIdentifier: "HKCategoryTypeIdentifierChills", kind: .category, name: "Chills", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "constipation", hkIdentifier: "HKCategoryTypeIdentifierConstipation", kind: .category, name: "Constipation", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "coughing", hkIdentifier: "HKCategoryTypeIdentifierCoughing", kind: .category, name: "Coughing", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "diarrhea", hkIdentifier: "HKCategoryTypeIdentifierDiarrhea", kind: .category, name: "Diarrhea", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "dizziness", hkIdentifier: "HKCategoryTypeIdentifierDizziness", kind: .category, name: "Dizziness", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "fainting", hkIdentifier: "HKCategoryTypeIdentifierFainting", kind: .category, name: "Fainting", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "fatigue", hkIdentifier: "HKCategoryTypeIdentifierFatigue", kind: .category, name: "Fatigue", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "fever", hkIdentifier: "HKCategoryTypeIdentifierFever", kind: .category, name: "Fever", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "headache", hkIdentifier: "HKCategoryTypeIdentifierHeadache", kind: .category, name: "Headache", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "heartburn", hkIdentifier: "HKCategoryTypeIdentifierHeartburn", kind: .category, name: "Heartburn", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "hot_flashes", hkIdentifier: "HKCategoryTypeIdentifierHotFlashes", kind: .category, name: "Hot Flashes", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "lower_back_pain", hkIdentifier: "HKCategoryTypeIdentifierLowerBackPain", kind: .category, name: "Lower Back Pain", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "loss_of_smell", hkIdentifier: "HKCategoryTypeIdentifierLossOfSmell", kind: .category, name: "Loss of Smell", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "loss_of_taste", hkIdentifier: "HKCategoryTypeIdentifierLossOfTaste", kind: .category, name: "Loss of Taste", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "mood_changes", hkIdentifier: "HKCategoryTypeIdentifierMoodChanges", kind: .category, name: "Mood Changes", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "nausea", hkIdentifier: "HKCategoryTypeIdentifierNausea", kind: .category, name: "Nausea", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "pelvic_pain", hkIdentifier: "HKCategoryTypeIdentifierPelvicPain", kind: .category, name: "Pelvic Pain", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "rapid_pounding_or_fluttering_heartbeat", hkIdentifier: "HKCategoryTypeIdentifierRapidPoundingOrFlutteringHeartbeat", kind: .category, name: "Rapid or Fluttering Heartbeat", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "runny_nose", hkIdentifier: "HKCategoryTypeIdentifierRunnyNose", kind: .category, name: "Runny Nose", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "shortness_of_breath", hkIdentifier: "HKCategoryTypeIdentifierShortnessOfBreath", kind: .category, name: "Shortness of Breath", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "sinus_congestion", hkIdentifier: "HKCategoryTypeIdentifierSinusCongestion", kind: .category, name: "Sinus Congestion", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "skipped_heartbeat", hkIdentifier: "HKCategoryTypeIdentifierSkippedHeartbeat", kind: .category, name: "Skipped Heartbeat", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "sleep_changes", hkIdentifier: "HKCategoryTypeIdentifierSleepChanges", kind: .category, name: "Sleep Changes", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "sore_throat", hkIdentifier: "HKCategoryTypeIdentifierSoreThroat", kind: .category, name: "Sore Throat", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "vomiting", hkIdentifier: "HKCategoryTypeIdentifierVomiting", kind: .category, name: "Vomiting", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "wheezing", hkIdentifier: "HKCategoryTypeIdentifierWheezing", kind: .category, name: "Wheezing", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "bladder_incontinence", hkIdentifier: "HKCategoryTypeIdentifierBladderIncontinence", kind: .category, name: "Bladder Incontinence", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "dry_skin", hkIdentifier: "HKCategoryTypeIdentifierDrySkin", kind: .category, name: "Dry Skin", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "hair_loss", hkIdentifier: "HKCategoryTypeIdentifierHairLoss", kind: .category, name: "Hair Loss", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "vaginal_dryness", hkIdentifier: "HKCategoryTypeIdentifierVaginalDryness", kind: .category, name: "Vaginal Dryness", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "memory_lapse", hkIdentifier: "HKCategoryTypeIdentifierMemoryLapse", kind: .category, name: "Memory Lapse", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "night_sweats", hkIdentifier: "HKCategoryTypeIdentifierNightSweats", kind: .category, name: "Night Sweats", category: .symptoms, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "environmental_audio_exposure_event", hkIdentifier: "HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent", kind: .category, name: "Loud Environment Events", category: .hearing, unit: "count", aggregation: .count, sensitivity: .standard),
        .init(key: "handwashing_event", hkIdentifier: "HKCategoryTypeIdentifierHandwashingEvent", kind: .category, name: "Handwashing", category: .other, unit: "min", aggregation: .duration, sensitivity: .standard),
        .init(key: "headphone_audio_exposure_event", hkIdentifier: "HKCategoryTypeIdentifierHeadphoneAudioExposureEvent", kind: .category, name: "Loud Headphone Events", category: .hearing, unit: "count", aggregation: .count, sensitivity: .standard),
        .init(key: "pregnancy", hkIdentifier: "HKCategoryTypeIdentifierPregnancy", kind: .category, name: "Pregnancy", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "lactation", hkIdentifier: "HKCategoryTypeIdentifierLactation", kind: .category, name: "Lactation", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "contraceptive", hkIdentifier: "HKCategoryTypeIdentifierContraceptive", kind: .category, name: "Contraceptive", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "low_cardio_fitness_event", hkIdentifier: "HKCategoryTypeIdentifierLowCardioFitnessEvent", kind: .category, name: "Low Cardio Fitness Events", category: .fitness, unit: "count", aggregation: .count, sensitivity: .standard),
        .init(key: "apple_walking_steadiness_event", hkIdentifier: "HKCategoryTypeIdentifierAppleWalkingSteadinessEvent", kind: .category, name: "Walking Steadiness Events", category: .mobility, unit: "count", aggregation: .count, sensitivity: .standard),
        .init(key: "pregnancy_test_result", hkIdentifier: "HKCategoryTypeIdentifierPregnancyTestResult", kind: .category, name: "Pregnancy Test Result", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "progesterone_test_result", hkIdentifier: "HKCategoryTypeIdentifierProgesteroneTestResult", kind: .category, name: "Progesterone Test Result", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "infrequent_menstrual_cycles", hkIdentifier: "HKCategoryTypeIdentifierInfrequentMenstrualCycles", kind: .category, name: "Infrequent Periods", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "irregular_menstrual_cycles", hkIdentifier: "HKCategoryTypeIdentifierIrregularMenstrualCycles", kind: .category, name: "Irregular Cycles", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "persistent_intermenstrual_bleeding", hkIdentifier: "HKCategoryTypeIdentifierPersistentIntermenstrualBleeding", kind: .category, name: "Persistent Intermenstrual Bleeding", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "prolonged_menstrual_periods", hkIdentifier: "HKCategoryTypeIdentifierProlongedMenstrualPeriods", kind: .category, name: "Prolonged Periods", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "bleeding_after_pregnancy", hkIdentifier: "HKCategoryTypeIdentifierBleedingAfterPregnancy", kind: .category, name: "Bleeding After Pregnancy", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "bleeding_during_pregnancy", hkIdentifier: "HKCategoryTypeIdentifierBleedingDuringPregnancy", kind: .category, name: "Bleeding During Pregnancy", category: .reproductive, unit: nil, aggregation: .latest, sensitivity: .sensitive),
        .init(key: "sleep_apnea_event", hkIdentifier: "HKCategoryTypeIdentifierSleepApneaEvent", kind: .category, name: "Sleep Apnea Notifications", category: .sleep, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "hypertension_event", hkIdentifier: "HKCategoryTypeIdentifierHypertensionEvent", kind: .category, name: "Hypertension Notifications", category: .vitals, unit: "count", aggregation: .count, sensitivity: .sensitive),
        .init(key: "workouts", hkIdentifier: "HKWorkoutTypeIdentifier", kind: .workout, name: "Workouts", category: .activity, unit: "count", aggregation: .count, sensitivity: .standard),
    ]

    /// Only what this device's OS actually supports.
    static let available: [MetricDescriptor] = all.filter { $0.objectType != nil }

    static let byKey: [String: MetricDescriptor] =
        Dictionary(uniqueKeysWithValues: all.map { ($0.key, $0) })

    static func inCategory(_ category: MetricCategory) -> [MetricDescriptor] {
        available.filter { $0.category == category }
            .sorted { $0.localizedName.localizedCompare($1.localizedName) == .orderedAscending }
    }
}
