"""Generate the Swift metric catalog and String Catalog from the SQL seed.

Single source of truth: supabase/migrations/0002_generic_metrics.sql plus
tools/metric_names_de.py. Re-run after changing either so the iOS app, the
German translations and the database can never drift apart.
"""
import re, sys, pathlib, json
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from metric_names_de import DE

ROOT = pathlib.Path(__file__).resolve().parent.parent
sql = (ROOT / "supabase/migrations/0002_generic_metrics.sql").read_text()
row = re.compile(
    r"^\s*\('([^']*)','([^']*)','([^']*)','([^']*)','([^']*)',(null|'[^']*'),'([^']*)','([^']*)'\)",
    re.M)
rows = row.findall(sql)
if len(rows) != 191:
    sys.exit(f"expected 191 catalog rows, parsed {len(rows)}")

names = [r[3] for r in rows]
dupes = {n for n in names if names.count(n) > 1}
if dupes:
    sys.exit(f"duplicate display names would collide as translation keys: {dupes}")
missing = {r[0] for r in rows} - set(DE)
if missing:
    sys.exit(f"missing German names for: {sorted(missing)}")

# category -> (SF Symbol, English title, German title)
CATEGORIES = {
    "activity":     ("figure.walk",                    "Activity",              "Aktivität"),
    "body":         ("figure.stand",                   "Body Measurements",     "Körpermaße"),
    "fitness":      ("figure.run",                     "Fitness",               "Fitness"),
    "hearing":      ("ear",                            "Hearing",               "Hören"),
    "heart":        ("heart.fill",                     "Heart",                 "Herz"),
    "lab":          ("testtube.2",                     "Lab Results",           "Laborwerte"),
    "mindfulness":  ("brain.head.profile",             "Mindfulness",           "Achtsamkeit"),
    "mobility":     ("figure.walk.motion",             "Mobility",              "Mobilität"),
    "nutrition":    ("fork.knife",                     "Nutrition",             "Ernährung"),
    "other":        ("square.grid.2x2",                "Other",                 "Sonstiges"),
    "reproductive": ("figure.dress.line.vertical.figure", "Reproductive Health","Reproduktive Gesundheit"),
    "respiratory":  ("lungs.fill",                     "Respiratory",           "Atmung"),
    "sleep":        ("bed.double.fill",                "Sleep",                 "Schlaf"),
    "symptoms":     ("stethoscope",                    "Symptoms",              "Symptome"),
    "vitals":       ("waveform.path.ecg",              "Vitals",                "Vitalzeichen"),
}
found = sorted({r[4] for r in rows})
if set(found) - set(CATEGORIES):
    sys.exit(f"category without icon/title: {set(found) - set(CATEGORIES)}")

def swift_opt(v):
    return "nil" if v == "null" else f'"{v[1:-1]}"'

entries = "\n".join(
    f'        .init(key: "{k}", hkIdentifier: "{i}", kind: .{kind}, '
    f'name: "{n}", category: .{c}, unit: {swift_opt(u)}, '
    f'aggregation: .{a}, sensitivity: .{s}),'
    for k, i, kind, n, c, u, a, s in rows)

cat_cases = "\n".join(f"    case {c}" for c in found)
cat_symbols = "\n".join(f'        case .{c}: "{CATEGORIES[c][0]}"' for c in found)
cat_titles = "\n".join(f'        case .{c}: "{CATEGORIES[c][1]}"' for c in found)

swift = f'''// Generated by tools/gen_catalog.py — do not edit by hand.
// Sources: supabase/migrations/0002_generic_metrics.sql, tools/metric_names_de.py
//
// Every HealthKit type the system knows about ({len(rows)} of them). Types resolve
// from their raw identifier at runtime rather than from compile-time enum cases,
// so a type that a given iOS version does not have simply resolves to nil and
// drops out of the picker instead of breaking the build.

import Foundation
import HealthKit

enum MetricKind: String, Sendable {{ case quantity, category, workout }}
enum MetricAggregation: String, Sendable {{ case sum, avg, latest, duration, count, max }}
enum MetricSensitivity: String, Sendable {{ case standard, sensitive }}

enum MetricCategory: String, Sendable, CaseIterable, Identifiable {{
{cat_cases}

    var id: String {{ rawValue }}

    var symbol: String {{
        switch self {{
{cat_symbols}
        }}
    }}

    /// English source string; the String Catalog supplies the German.
    private var sourceTitle: String {{
        switch self {{
{cat_titles}
        }}
    }}

    var title: String {{ String(localized: .init(sourceTitle)) }}
}}

struct MetricDescriptor: Sendable, Hashable, Identifiable {{
    let key: String
    let hkIdentifier: String
    let kind: MetricKind
    let name: String
    let category: MetricCategory
    let unit: String?
    let aggregation: MetricAggregation
    let sensitivity: MetricSensitivity

    var id: String {{ key }}

    /// Looked up at runtime because `name` is data, not a literal.
    var localizedName: String {{ String(localized: .init(name)) }}

    /// The HealthKit type to request, or nil when this OS has no such type.
    var objectType: HKObjectType? {{
        switch kind {{
        case .quantity:
            HKObjectType.quantityType(forIdentifier: .init(rawValue: hkIdentifier))
        case .category:
            HKObjectType.categoryType(forIdentifier: .init(rawValue: hkIdentifier))
        case .workout:
            HKObjectType.workoutType()
        }}
    }}
}}

enum MetricCatalog {{
    static let all: [MetricDescriptor] = [
{entries}
    ]

    /// Only what this device's OS actually supports.
    static let available: [MetricDescriptor] = all.filter {{ $0.objectType != nil }}

    static let byKey: [String: MetricDescriptor] =
        Dictionary(uniqueKeysWithValues: all.map {{ ($0.key, $0) }})

    static func inCategory(_ category: MetricCategory) -> [MetricDescriptor] {{
        available.filter {{ $0.category == category }}
            .sorted {{ $0.localizedName.localizedCompare($1.localizedName) == .orderedAscending }}
    }}
}}
'''
(ROOT / "ios/Wavelet/Sources/Health/MetricCatalog.generated.swift").write_text(swift)

# ---- String Catalog -------------------------------------------------------
UI = json.loads((ROOT / "tools/ui_strings_de.json").read_text())
strings = {}
def add(en, de):
    strings[en] = {"extractionState": "manual", "localizations": {
        "de": {"stringUnit": {"state": "translated", "value": de}}}}

for k, _i, _kind, n, _c, _u, _a, _s in rows:
    add(n, DE[k])
for _c, (_sym, en, de) in CATEGORIES.items():
    add(en, de)
for en, de in UI.items():
    add(en, de)

catalog = {"sourceLanguage": "en", "strings": dict(sorted(strings.items())), "version": "1.0"}
(ROOT / "ios/Wavelet/Sources/Support/Localizable.xcstrings").write_text(
    json.dumps(catalog, ensure_ascii=False, indent=2))

print(f"catalog: {len(rows)} metrics, {len(found)} categories")
print(f"strings: {len(strings)} localized keys (metrics + categories + UI)")
